### ISSUE TITLE
Load metadata in StreamrSubscribe

### ISSUE THREAD

**Issue by mabdi** [streamr-dev/streamr-nifi#2]
Dear @juslesan 

I need the timestamp of the data. How can I access metadata?

**Comment by juslesan** [comment]
Hi @mabdi !
The metadata was included to the attributes of the flow file, but it turned out to be a bit harder than intended to utilize the metadata. So, I made some changes to the StreamrSubscribe module so that now you can choose to include metadata to the content of the flow file.

Just redownload and setup the .nar file and restart NiFi. Then go to the properties tab of the processor. You'll find a new "metadata" field there. You can choose to add all of the metadata or just the Streamr timestamp!

**Comment by mabdi** [comment]
Tnx. It's great now.
